### ISSUE TITLE
Source map example

### ISSUE THREAD

**Issue by sanjitkung** [tclindner/sentry-releases-action#93]
Thanks for the awesome work. 

I am very new to actions. Can you please provide me an example on how I can upload source maps?

**Comment by tclindner** [comment]
@sanjitkung Yeah. I’ll try to get one posted in the next day or so.

**Comment by tclindner** [comment]
Hey @sanjitkung! Can you please let me know if this example helps? 
https://github.com/tclindner/sentry-releases-action/blob/master/README.md#example-workflow-with-optional-sourcemap-upload

Thank you!

**Comment by sanjitkung** [comment]
Yes .. Thank you so much :)

**Comment by tclindner** [comment]
Let us know if you have any other questions or ideas for the action!

**Comment by jonathan3692bf** [comment]
This example is technically wrong; I used it and Github complained that `A mapping was not expected`. So intead, you'll need to wrap the string in quotes (for JSON to later parse).

For example, pay attention to `sourceMapOptions`, which is single quoted for YAML to recognize it is a string, but double quoted on the interior to make sure that it is still valid JSON.

```yaml
name: ReleaseWorkflow

on:
  release:
    types: [published, prereleased]


jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: myAwesomeOrg
          SENTRY_PROJECT: myAwesomeProject
        with:
          tagName: ${{ github.ref }}
          environment: qa
          releaseNamePrefix: myAwesomeProject-
          sourceMapOptions: '{"include": ["build"]}'`
```
