### ISSUE TITLE
Unexpected input 'releaseNamePrefix', valid inputs are ['tagName', 'environment']

### ISSUE THREAD

**Issue by sanjitkung** [tclindner/sentry-releases-action#94]
I am getting this error  when trying to add release prefix
```
Unexpected input 'releaseNamePrefix', valid inputs are ['tagName', 'environment']
```

Here is my action file

```
name: ReleaseWorkFlow

on:
  release:
    types: [published, prereleased]

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Create a Sentry release
        uses: tclindner/sentry-releases-action@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: xyz
          SENTRY_PROJECT: abc
        with:
          tagName: ${{ github.ref }}
          environment: production
          releaseNamePrefix: main-

      - name: Create a deploy for a Sentry.io release
        uses: tclindner/sentry-release-deploy-action@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: xyz
          SENTRY_PROJECT: abc
        with:
          version: ${{ github.ref }}
          environment: production
          versionPrefix: main-
```

Is there something I am doing wrong? Please help!
